# Generated by Django 4.0.3 on 2022-04-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='ism')),
                ('phone', models.BigIntegerField(verbose_name='telefon raqam')),
            ],
        ),
        migrations.CreateModel(
            name='Comforts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room_comforts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='ism')),
                ('state', models.CharField(max_length=100, verbose_name='viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='tuman')),
                ('street', models.CharField(max_length=200, verbose_name='manzil')),
                ('image', models.ImageField(upload_to='images', verbose_name='rasm')),
                ('about', models.TextField(verbose_name='mehmonhona haqida')),
                ('additional', models.ManyToManyField(to='Site.additional', verbose_name="Qo'shimcha hizmatlar")),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.agent', verbose_name='ishchi')),
                ('comforts_list', models.ManyToManyField(to='Site.comforts', verbose_name='qulayliklar')),
                ('distance', models.ManyToManyField(to='Site.distance', verbose_name='markazdan masofa')),
                ('rating', models.ManyToManyField(to='Site.rating', verbose_name='reyting')),
                ('room_comforts', models.ManyToManyField(to='Site.room_comforts', verbose_name='Xonadagi qulayliklar')),
                ('types', models.ManyToManyField(to='Site.room_type', verbose_name='xonalar turi')),
            ],
        ),
    ]
