# Generated by Django 4.0.3 on 2022-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_grading_hotel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='grade',
            field=models.ManyToManyField(blank=True, null=True, to='Site.grading', verbose_name='baho'),
        ),
    ]
