# Generated by Django 4.0.4 on 2022-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_alter_hotel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='average',
            field=models.IntegerField(blank=True, null=True, verbose_name="o'rtacha baho"),
        ),
        migrations.AlterField(
            model_name='grading',
            name='grade',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='baho'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='grade',
            field=models.ManyToManyField(blank=True, to='Site.grading', verbose_name='baho'),
        ),
    ]
