# Generated by Django 4.0.4 on 2022-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_hotel_average_alter_grading_grade_alter_hotel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name="o'rtacha baho"),
        ),
    ]
