# Generated by Django 4.0.4 on 2022-04-28 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0005_alter_hotel_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='viewed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="ko'rilgan"),
        ),
        migrations.AddField(
            model_name='hotel',
            name='viewed_count',
            field=models.IntegerField(blank=True, default=0, verbose_name="ko'rilgan soni"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grading',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='baho'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='average',
            field=models.FloatField(default=0, verbose_name="o'rtacha baho"),
            preserve_default=False,
        ),
    ]
