# Generated by Django 4.0.4 on 2022-05-27 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0006_hotel_viewed_hotel_viewed_count_alter_grading_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='hona nomi')),
                ('capacity', models.IntegerField(verbose_name="hona sig'imi")),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='...dan')),
                ('check_out', models.DateField(verbose_name='...gacha')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.room', verbose_name='hona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='buyurtmachi')),
            ],
        ),
    ]
