# Generated by Django 4.0.4 on 2022-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(to='Site.room', verbose_name='honalar'),
        ),
    ]
