# Generated by Django 4.0.4 on 2022-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_hotel_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='otel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='booked_rooms',
            field=models.ManyToManyField(blank=True, to='Site.booking', verbose_name='zakaz honalar'),
        ),
    ]
