# Generated by Django 4.0.4 on 2022-05-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_remove_grading_otel_hotel_booked_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='otel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Site.hotel', verbose_name='Otel nomi'),
            preserve_default=False,
        ),
    ]
